name: Limpiar documentos

on:
  push:
    paths:
      - "docs/**/*.md"           # vigila docs/
  workflow_dispatch:

permissions:
  contents: write               # permite hacer push

jobs:
  curar:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Python + Pandoc
      - name: Instalar dependencias
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          pip install openai==0.28.1

      # 3. Limpiar Markdown con GPT
      - name: Ejecutar limpiador
        env:
          OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        run: python .github/scripts/curate_docs.py

      # 4. Construir PDF y DOCX
      - name: Construir PDF y DOCX
        run: |
          mkdir -p build
          pandoc docs/**/*.md -s -o build/Biblia-CG.pdf
          pandoc docs/**/*.md -s -o build/Biblia-CG.docx

      # 5. Subir artefactos
      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: biblia-build
          path: build/

      # 6. Hacer commit push de correcciones
      - name: Commit cambios curados
        env:
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          if git diff --quiet docs; then
            echo "Sin cambios"
          else
            git config user.name  "robot-docs"
            git config user.email "robot@example.com"
            git add docs
            git commit -m "docs: autocuración"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.ref }}
          fi
