name: Limpiar documentos
on:
  push:
    paths: ["docs/**/*.md"]          # vigila la carpeta docs/
  workflow_dispatch:                 # botón Run workflow opcional

jobs:
  curar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Instala versión antigua del SDK que admite ChatCompletion.create
      - run: pip install openai==0.28.1

      - run: python .github/scripts/curate_docs.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
