name: Limpiar documentos
on:
  push:
    paths: ["docs/**/*.md"]
  workflow_dispatch:

permissions:
  contents: write            # ← permite que el workflow haga push

jobs:
  curar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - run: pip install openai==0.28.1     # SDK compatible

      - run: python .github/scripts/curate_docs.py
        env: { OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} }

      - name: Commit cambios curados
        run: |
          if git diff --quiet; then
            echo "Sin cambios."
          else
            git config user.name  "robot-docs"
            git config user.email "robot@example.com"
            git add docs
            git commit -m "docs: autocuración"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD
          fi
