name: Limpiar documentos

on:
  push:
    paths:
      - 'docs/**/*.md'      # vigila la carpeta docs/
  workflow_dispatch:

permissions:
  contents: write           # permite que el workflow haga push

jobs:
  curar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false   # usamos un token limpio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install openai==0.28.1   # SDK compatible

      - name: Ejecutar limpiador
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/curate_docs.py

      - name: Commit cambios curados
        run: |
          if git diff --quiet docs; then
            echo "Sin cambios"
          else
            git config user.name  "robot-docs"
            git config user.email "robot@example.com"
            git add docs
            git commit -m "docs: autocuración"
            git push
          fi
